{% set version = "2.2.0" %}

package:
  name: bob.measure
  version: {{ version }}

source:
  fn: bob.measure-{{ version }}.zip
  md5: 8191501e4c3c4ffdded42b37922b1628
  url: https://pypi.io/packages/source/b/bob.measure/bob.measure-{{ version }}.zip

build:
  entry_points:
    - bob_compute_perf.py = bob.measure.script.compute_perf:main
    - bob_eval_threshold.py = bob.measure.script.eval_threshold:main
    - bob_apply_threshold.py = bob.measure.script.apply_threshold:main
    - bob_plot_cmc.py = bob.measure.script.plot_cmc:main
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - bob.extension
    - bob.blitz
    - bob.core >2.0.4
    - bob.math
    - bob.io.base
    - matplotlib
    - pkg-config
    - boost 1.61.*
    - docopt

  run:
    - python
    - bob.extension
    - bob.blitz
    - bob.core >2.0.4
    - bob.math
    - bob.io.base
    - matplotlib
    - boost 1.61.*
    - docopt

test:
  commands:
    - bob_compute_perf.py --help
    - bob_eval_threshold.py --help
    - bob_apply_threshold.py --help
    - bob_plot_cmc.py --help
    - nosetests -sv bob.measure

  imports:
    - bob
    - bob.measure
    - bob.measure.script

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Bob's evalution metrics

extra:
  recipe-maintainers:
    - 183amir
